services:
  epp-local-test:
    image: epp-local-test:latest
    build:
      context: .
    container_name: epp-local-test
    hostname: epp-local-test
    environment:
      - FLASK_ENV=development
    command: ["python", "auto.py"]
    #command: ["/bin/sh", "-c", "set -e && echo \"Starting\" && gunicorn --chdir /app/src auto:app -b 0.0.0.0:7000"]
    ports:
      - "7000:7000"

networks:
  default:

