apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: rag-pipeline-20241118
  annotations:
    scenarios.ai.sap.com/description: "RAG Pipeline"
    scenarios.ai.sap.com/name: "rag-pipeline"
    executables.ai.sap.com/description: "RAG Pipeline: retriever, building prompt, generation"
    executables.ai.sap.com/name: "rag-pipeline-executable"
  labels:
    scenarios.ai.sap.com/id: "rag-pipeline"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters:
      - name: myResourcePlan
        type: string
        default: starter
      - name: AICORE_AUTH_URL
        type: string
      - name: AICORE_CLIENT_ID
        type: string
      - name: AICORE_CLIENT_SECRET
        type: string
      - name: AICORE_BASE_URL
        type: string
      - name: AICORE_RESOURCE_GROUP
        type: string
      - name: ORC_API_URL
        type: string
      - name: HANA_DB_HOST
        type: string
      - name: HANA_DB_USER
        type: string
      - name: HANA_DB_PASSWORD
        type: string
      - name: HANA_DB_TABLE_NAME
        type: string
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: "{{inputs.parameters.myResourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
          - name: my-dockerhub-secret
        minReplicas: 1
        maxReplicas: 5
        containers:
        - name: kserve-container
          image: docker.io/kevinxhuang/rag-pipeline:latest
          command: ["python3", "main.py"]
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: AICORE_AUTH_URL
              value: "{{inputs.parameters.AICORE_AUTH_URL}}"
            - name: AICORE_CLIENT_ID
              value: "{{inputs.parameters.AICORE_CLIENT_ID}}"
            - name: AICORE_CLIENT_SECRET
              value: "{{inputs.parameters.AICORE_CLIENT_SECRET}}"
            - name: AICORE_BASE_URL
              value: "{{inputs.parameters.AICORE_BASE_URL}}"
            - name: AICORE_RESOURCE_GROUP
              value: "{{inputs.parameters.AICORE_RESOURCE_GROUP}}"
            - name: ORC_API_URL
              value: "{{inputs.parameters.ORC_API_URL}}"
            - name: HANA_DB_HOST
              value: "{{inputs.parameters.HANA_DB_HOST}}"
            - name: HANA_DB_USER
              value: "{{inputs.parameters.HANA_DB_USER}}"
            - name: HANA_DB_PASSWORD
              value: "{{inputs.parameters.HANA_DB_PASSWORD}}"
            - name: HANA_DB_TABLE_NAME
              value: "{{inputs.parameters.HANA_DB_TABLE_NAME}}"
